### ISSUE TITLE
How to draw the superpixels?

### ISSUE THREAD

**Issue by luomomo** [TingmanYan/FDR#2]
It seems that one of the difference if this paper with localexp is that you use superpixels. But I wonder how to draw out the superpixels edge? Or you just use the mean value of the superpixel so the segmentation accuraccy do not  affect too much?

**Comment by TingmanYan** [comment]
Hi, the superpixel label is stored in the cv::Mat spx. You can use spx.at<int>(y, x) to access per-pixel label info. An edge-pixel has its label different from its neighbors.

**Comment by ynma-hanvo** [comment]
great work.  but it seems to be too slow for realtime.

**Comment by luomomo** [comment]
O(∩_∩)O非常感谢您给我发来邮件，稍后我会仔细阅读。
