### ISSUE TITLE
by  the  way ，if  I want to   use my own picture to  calculate the disparity  via  your excellent  methods，what should I do ，because I AM a  freshman，thank  you very much！！！

### ISSUE THREAD

**Issue by Luo-Zhongwei** [TingmanYan/FDR#5]

**Comment by TingmanYan** [comment]
You need to calculate the WTA disparity map by first computing the cost volume. And then modify **main.cpp** to invoke the `fdr->run()` on a single image.

**Comment by zpp1996** [comment]
请问您跑通这个代码了吗？我可以请教一些问题吗？请问您是修改了哪部分代码可以测试自己的图片呢？能分享一份给我吗？我的邮箱是1258681798@qq.com 谢谢~
