### ISSUE TITLE
how can I code for vs2017

### ISSUE THREAD

**Issue by zhenghao222** [TingmanYan/FDR#6]
I look for your codes(fdr/main.cpp)，which is for KITTI dataset.
Now i want to refine my own disparity(CV_8U),how to modify this ?

**Comment by TingmanYan** [comment]
You can modify main.cpp, where MidV3 and KITTI are two interface functions, they all invoke the run function of class FastDR
```
FastDR* fdr = new FastDR(im0, disp_WTA, params, max_disp, 0);
cv::Mat labeling, refined_disp;
fdr->run(labeling, refined_disp);
```
where im0 is the reference left color image, disp_WTA is your disparity, and params can be left as default.

**Comment by zhenghao222** [comment]
And what these two input images' type and channels requested?
 COLOR OR GRAY?
CV8U OR CV32FC1?
because i find that there may exist exceptions error in fdr->run function

**Comment by TingmanYan** [comment]
CV_8UC3 and CV_32FC1 for color and disparity images, respectively.

**Comment by zhenghao222** [comment]
void SurfaceFitting::computeCurve(const cv::Mat& D, const cv::Mat& rgn,
                                  float** curve) {
    for (int i = 0; i < height; i++)
        for (int j = 0; j < width; j++){
            int tl = rgn.at<int>(i, j);
            int disp = D.at<float>(i, j);
            curve[tl][disp] += 1;
        }
}

thanks for your reply!
i'm so upset that exists some exceptions run in conputeCurve()

**Comment by TingmanYan** [comment]
It shall be `rgn.at<int>(i, j) and D.at<float>(i, j)`
make sure the type matches.
And your maximum disparity shall be less than (not equal to) MAX_DISPARITY.

**Comment by zhenghao222** [comment]
Yeah！
Due to your latest reply, it can work well in my vs2017. 
Because I set a large max_disp value,like=300. 
And when computing disparity map, i set my own disp_size = 64 or 128 or 256.
Can you explain the relationship between SDR algorithm max_disp and SGM disp_size.
Thanks a lot!!!

**Comment by zhenghao222** [comment]
![libSGM](https://user-images.githubusercontent.com/44895543/103346856-4965e680-4ad0-11eb-8752-4729ddff0503.PNG)
only libSGM
![libSGM+SDR](https://user-images.githubusercontent.com/44895543/103346872-51be2180-4ad0-11eb-893d-013d8f8e7ec2.PNG)
libSGM + SDR
![libSGM+WLS+SDR](https://user-images.githubusercontent.com/44895543/103346886-571b6c00-4ad0-11eb-9847-d8dfe7d01289.PNG)
libSGM + WLS + SDR

**Comment by TingmanYan** [comment]
> Yeah！
> Due to your latest reply, it can work well in my vs2017.
> Because I set a large max_disp value,like=300.
> And when computing disparity map, i set my own disp_size = 64 or 128 or 256.
> Can you explain the relationship between SDR algorithm max_disp and SGM disp_size.
> Thanks a lot!!!

max_disp and disp_size shall be the same.
By the way, I can't view your image on Github, you'd better send it to my email.

**Comment by zpp1996** [comment]
> I look for your codes(fdr/main.cpp)，which is for KITTI dataset. Now i want to refine my own disparity(CV_8U),how to modify this ?

我可以请教你一些关于运行这个代码的问题嘛？我按照read me上面的步骤打开fdr.sln，不知道该如何运行main.cpp?

**Comment by zpp1996** [comment]
请问您是如何测试自己的图片的？我测试自己的图片，发生了错误，是MAX_DISPARITY导致了，我输出的值是一个负值，请问您有遇到这个错误吗？

**Comment by zpp1996** [comment]
我想请问一下 max_disp这个参数的大小应该如何设置？我设置该参数不合适的时候，会报错，对于自己的图片，你是如何设置该参数的呢？

**Comment by luomomo** [comment]
O(∩_∩)O非常感谢您给我发来邮件，稍后我会仔细阅读。
