### ISSUE TITLE
Hello，when I run main.cpp with vs2017,I get a exception in FastDR.cpp

### ISSUE THREAD

**Issue by WildEgoLee** [TingmanYan/FDR#7]
I can run demo.bat with no error,but when I run main.cpp with my own image,I  get a exception in FastDR.cpp 186 line.the wrong code is the last line: 
 for (int i = 0; i < height; i++)
        for (int j = 0; j < width; j++) {
            tl = spx.at<int>(i, j);
            int disp = D.at<float>(i, j);
            data_term[tl][disp / bins_width] += 1;
        }
Wish you can give me some helps.

**Comment by TingmanYan** [comment]
I think you should check the parameter of _maxdisp_ and maybe change it to _maxdisp - 1_ ?

**Comment by WildEgoLee** [comment]
Thanks for reply.When I change maxdisp to maxdisp-1,the error is same ;then I try change maxdisp to a large number like 200,the error became "Data cost term was larger than GCO_MAX_ENERGYTERM; danger of integer overflow".

**Comment by TingmanYan** [comment]
What's the resolution and maximum disparity of your input disparity map? Please give more details and maybe I can help.

**Comment by WildEgoLee** [comment]
The resolution is 1436x992, maximum disparity is 73,First I run SGM to get the disparity map and let its maximum disparity is 72.Then I run the main.cpp in SDR with this disparity map,I got a error.

**Comment by TingmanYan** [comment]
Hi. I think it is the datatype of the disparity map does not match. The code use float type as
`int disp = D.at<float>(i, j);`
Maybe your disparity map is stored as int or uchar? You can change the `float' to the corresponding type.
