### ISSUE TITLE
请问calib.txt里面的参数是什么？如何能够得到这个文件呢？您在data中放的数据集的链接，我打不开，您可以重新发一个吗？

### ISSUE THREAD

**Issue by zpp1996** [TingmanYan/FDR#8]

**Comment by luomomo** [comment]
O(∩_∩)O非常感谢您给我发来邮件，稍后我会仔细阅读。

**Comment by zpp1996** [comment]
请问如果测试自己的图片，是否需要calib.txt文件？
我没有设置calib.txt测试了自己的图片，结果报错了
我输出了一下MAX_DISPARITY,结果是一个负值-916913944，请问这个参数是什么含义？

**Comment by zpp1996** [comment]
请问如果测试自己的图片，是否需要calib.txt文件？
我没有设置calib.txt测试了自己的图片，结果报错了
我输出了一下MAX_DISPARITY,结果是一个负值-916913944，请问这个参数是什么含义？

**Comment by zpp1996** [comment]
我想请问一下 max_disp这个参数的大小应该如何设置？我设置该参数不合适的时候，会报错，对于自己的图片，该如何设置这个参数的大小呢？
